name: documentation

on:
  push:
    branches: [ "master" , "v2.X" ]
permissions:
  contents: write

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Get PythonPath and PWD
        run: |
          echo "PWD=$(pwd)"
          echo "PYTHONPATH=$PYTHONPATH"
      - name: Sphinx build
        run: |
          cd sdmxthon
          echo "PWD=$(pwd)"
          echo "FILES=$(find . -type f -printf "%f\n)"
          sphinx-build docs docs/_build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'sdmxthon/docs/_build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
