name: documentation

on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Sphinx build
        run: |
          pipenv run sphinx-build sdmxthon/docs _build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # upload entire directory
          path: '_build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


