# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  testing-and-flake8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pipenv
          pipenv install
      - name: Run test suite
        run: |
          pipenv run pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Flake8 errors
          flake8 . --count --max-complexity=25 --max-line-length=81 --show-source --statistics
